# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ian Doran
tagline:          'My Coding Journey'
description:      'A rambling document following my journey as I learn to code.'
url:              
baseurl:          /

author:
  name:           'Ian Doran'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           
